algoritmo "semnome"



var
    i,j,k,z:inteiro

inicio
    para i de 1 ate 3 faca
        escreva("i",i)
        para j de 1 ate 10 faca
            escreva("j",j)
            para k de 1 ate 10 faca
                escreva("k",k)
            fimpara
            escreval("Fim k")
        fimpara
        escreval("Fim j")
        para z de 1 ate 5 faca
            escreva("z",z)
        fimpara
        escreval("Fim z")
        escreval("Fim i")
    fimpara

fimalgoritmo
